# Generated by Django 6.0.2 on 2026-03-03 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Puesto')),
                ('company', models.CharField(max_length=200, verbose_name='Empresa')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('short_description', models.CharField(max_length=300, verbose_name='Descripción corta')),
                ('location', models.CharField(max_length=200, verbose_name='Lugar')),
                ('salary', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sueldo')),
                ('modality', models.CharField(choices=[('presencial', 'Presencial'), ('remoto', 'Remoto'), ('hibrido', 'Híbrido')], default='presencial', max_length=20, verbose_name='Modalidad')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de publicación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Oferta de trabajo',
                'verbose_name_plural': 'Ofertas de trabajo',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de suscripción')),
            ],
            options={
                'verbose_name': 'Suscriptor',
                'verbose_name_plural': 'Suscriptores',
                'ordering': ['-created_at'],
            },
        ),
    ]
