# Generated by Django 6.0.4 on 2026-04-21 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_job_benefits_job_email_job_experience_job_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('category', models.CharField(help_text='Ej: Entrevistas, Salario, Carrera.', max_length=60, verbose_name='Categoría')),
                ('badge', models.CharField(default='Guía', max_length=40, verbose_name='Badge')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('image_url', models.URLField(verbose_name='URL de imagen')),
                ('read_time', models.CharField(default='5 min lectura', max_length=30, verbose_name='Tiempo de lectura')),
                ('url', models.URLField(verbose_name='Enlace del artículo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de publicación')),
            ],
            options={
                'verbose_name': 'Artículo',
                'verbose_name_plural': 'Artículos',
                'ordering': ['order', '-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('curso', 'Curso'), ('libro', 'Libro'), ('tool', 'Herramienta'), ('promo', 'Oferta')], default='curso', max_length=20, verbose_name='Tipo')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.CharField(max_length=300, verbose_name='Descripción')),
                ('url', models.URLField(verbose_name='Enlace de afiliado')),
                ('emoji', models.CharField(default='⭐', help_text='Se muestra como placeholder de imagen.', max_length=10, verbose_name='Emoji / icono')),
                ('gradient', models.CharField(blank=True, default='', help_text='Opcional: linear-gradient(...). Vacío = gradient por defecto.', max_length=200, verbose_name='Gradient CSS')),
                ('price', models.CharField(blank=True, default='', max_length=50, verbose_name='Precio')),
                ('price_old', models.CharField(blank=True, default='', max_length=50, verbose_name='Precio anterior / tachado')),
                ('cta_label', models.CharField(default='Ver curso', max_length=50, verbose_name='Texto del botón')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Recurso',
                'verbose_name_plural': 'Recursos',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
