# Generated by Django 6.0.4 on 2026-04-22 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_articulo_recurso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='recurso',
            name='emoji',
        ),
        migrations.RemoveField(
            model_name='recurso',
            name='gradient',
        ),
        migrations.AddField(
            model_name='articulo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='articulos/', verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='recurso',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recursos/', verbose_name='Imagen'),
        ),
    ]
