# Generated by Django 6.0.4 on 2026-05-07 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_articulo_image_url_remove_recurso_emoji_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='application_link',
            field=models.URLField(blank=True, null=True, verbose_name='Link de aplicación'),
        ),
    ]
