# Generated by Django 6.0.4 on 2026-05-14 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_job_application_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='content',
            field=models.TextField(blank=True, default='', help_text='Contenido HTML del artículo completo.', verbose_name='Contenido'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='slug',
            field=models.SlugField(default='temp-slug', help_text='URL amigable, ej: entrevista-tecnica-7-dias', max_length=220, unique=True, verbose_name='Slug'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articulo',
            name='description',
            field=models.TextField(verbose_name='Descripción corta'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='url',
            field=models.URLField(blank=True, default='', verbose_name='Enlace externo (opcional)'),
        ),
    ]
