# Generated by Django 6.0.2 on 2026-03-13 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0002_incomingjob_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomingjob',
            name='job_created',
            field=models.BooleanField(default=False),
        ),
    ]
