# Generated by Django 6.0.4 on 2026-04-21 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0003_incomingjob_job_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incomingjob',
            options={'ordering': ['-created_at'], 'verbose_name': 'Oferta entrante', 'verbose_name_plural': 'Ofertas entrantes'},
        ),
        migrations.AlterField(
            model_name='incomingjob',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Recibido en'),
        ),
        migrations.AlterField(
            model_name='incomingjob',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='incoming_jobs/', verbose_name='Imagen adjunta'),
        ),
        migrations.AlterField(
            model_name='incomingjob',
            name='job_created',
            field=models.BooleanField(default=False, verbose_name='Oferta creada'),
        ),
        migrations.AlterField(
            model_name='incomingjob',
            name='raw_message',
            field=models.TextField(verbose_name='Mensaje original'),
        ),
        migrations.AlterField(
            model_name='incomingjob',
            name='source',
            field=models.CharField(default='whatsapp', max_length=100, verbose_name='Fuente'),
        ),
        migrations.AlterField(
            model_name='incomingjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado')], default='pending', max_length=20, verbose_name='Estado'),
        ),
    ]
