# Generated by Django 6.0.4 on 2026-05-07 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0004_alter_incomingjob_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomingjob',
            name='duplicate_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='automation.incomingjob', verbose_name='Duplicado de'),
        ),
        migrations.AlterField(
            model_name='incomingjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('duplicated', 'Duplicado'), ('spam', 'Spam'), ('incomplete', 'Incompleto')], default='pending', max_length=20, verbose_name='Estado'),
        ),
    ]
